version = 0.1

[default.deploy.parameters]
stack_name = "chespirito-api-spring"
resolve_s3 = true
s3_prefix = "chespirito-api-spring"
profile = ""
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-1"
